### ISSUE TITLE
Erreur: Failed to update files on (un)publishing: Topic not found

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#183]
Dans le cas où l'on ajoute un article, au moment de publier cette erreur survient : 
`Erreur: Failed to update files on (un)publishing: Topic not found`

Alors que le champs topic est bien rempli à partir de la liste déroulante.

Résultat impossible de publier...

**Comment by naholyr** [comment]
C'est une erreur récente ? En prod ou en dév ?

**Comment by naholyr** [comment]
Les noms des topics ont-ils bien été saisis dans les deux langues ? C'est une erreur qui se produit si le topic n'a pas été trouvé, mais aussi (et le message est plus confus dans ce cas) s'il n'a pas de nom dans la langue demandée

**Comment by TomBor** [comment]
Possiblement en lien avec #181.
Une réindexation réglera peut-être le problème (@jri-sp)

yarn es-index reindex topics


Le lun. 29 oct. 2018 18:58, Nicolas Chambrier <notifications@github.com> a
écrit :

**Comment by jri-sp** [comment]
J'ai cette erreur:
```
/eatlas/server # npm run es-index reindex topics

> server@1.0.0 es-index /eatlas/server
> cross-env 'NODE_CONFIG_DIR=${NODE_CONFIG_DIR:../config}' node bin/es-index.js "reindex" "topics"

{"name":"eatlas","hostname":"65215912ec7e","pid":225,"domain":"elasticsearch","level":30,"msg":"Adding connection to http://es:9200/","time":"2018-10-30T08:44:30.536Z","v":0}
{ Error: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="topics" & index_uuid="_na_" & index="topics" }
    at respond (/eatlas/server/node_modules/elasticsearch/src/lib/transport.js:307:15)
    at checkRespForFailure (/eatlas/server/node_modules/elasticsearch/src/lib/transport.js:266:7)
    at HttpConnector.<anonymous> (/eatlas/server/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/eatlas/server/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  status: 404,
  displayName: 'NotFound',
  message: '[index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="topics" & index_uuid="_na_" & index="topics" }',
  path: '/topics/_alias',
  query: {},
  body:
   { error:
      { root_cause: [Array],
        type: 'index_not_found_exception',
        reason: 'no such index',
        'resource.type': 'index_or_alias',
        'resource.id': 'topics',
        index_uuid: '_na_',
        index: 'topics' },
     status: 404 },
  statusCode: 404,
  response: '{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"topics","index_uuid":"_na_","index":"topics"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"topics","index_uuid":"_na_","index":"topics"},"status":404}',
  toString: [Function],
  toJSON: [Function] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 es-index: `cross-env 'NODE_CONFIG_DIR=${NODE_CONFIG_DIR:../config}' node bin/es-index.js "reindex" "topics"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@1.0.0 es-index script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-30T08_44_30_614Z-debug.log
```

Est-ce qu'il y a des paramètres à passer, ou une doc sur l'utilisation de la commande ?

**Comment by TomBor** [comment]
C'est ma faute, j'ai écris depuis mon téléphone, les index sont au singulier du coup c'est : 
`yarn es-index reindex topic`

Sinon la doc est ici https://github.com/AtelierCartographie/eatlas/blob/master/docs/Maintenance.md#manipuler-les-indices-elastic-search

**Comment by jri-sp** [comment]
Ah ok merci! 

Du coup la commande est bien passée:
```
/eatlas/server # npm run es-index reindex topic

> server@1.0.0 es-index /eatlas/server
> cross-env 'NODE_CONFIG_DIR=${NODE_CONFIG_DIR:../config}' node bin/es-index.js "reindex" "topic"

{"name":"eatlas","hostname":"65215912ec7e","pid":251,"domain":"elasticsearch","level":30,"msg":"Adding connection to http://es:9200/","time":"2018-10-30T08:51:59.478Z","v":0}
{"name":"eatlas","hostname":"65215912ec7e","pid":251,"domain":"elasticsearch-index-migration","level":40,"msg":"Obsolete mapping","time":"2018-10-30T08:51:59.541Z","v":0}
{"name":"eatlas","hostname":"65215912ec7e","pid":251,"domain":"elasticsearch-index-migration","level":30,"msg":"Automatic index upgrade…","time":"2018-10-30T08:51:59.542Z","v":0}
{"name":"eatlas","hostname":"65215912ec7e","pid":251,"domain":"elasticsearch-index-migration","level":30,"msg":"Reindexing into eatlas_topic_1540889519542…","time":"2018-10-30T08:52:00.022Z","v":0}
{"name":"eatlas","hostname":"65215912ec7e","pid":251,"domain":"elasticsearch-index-migration","level":30,"msg":"Aliased index: update alias eatlas_topic → eatlas_topic_1540889519542, then drop eatlas_topic_1536743679991…","time":"2018-10-30T08:52:00.103Z","v":0}
New index "eatlas_topic_1540889519542"
OK.
```

J'ai tenté de refaire un rebuild-site après ça, mais j'ai toujours la même erreur:
```
{"name":"eatlas","hostname":"65215912ec7e","pid":284,"level":60,"err":{"message":"Topic not found","name":"Error","stack":"Error: Topic not found\n    at getTopicSlug (/eatlas/server/lib/resource-path.js:21:11)\n    at exports.pagePath (/eatlas/server/lib/resource-path.js:37:11)\n    at resource (/eatlas/server/lib/generator-utils.js:86:19)\n    at exports.getUrl (/eatlas/server/lib/generator-utils.js:407:64)\n    at render (/eatlas/server/lib/html-generator.js:93:26)\n    at exports.generateTopicHTML (/eatlas/server/lib/html-generator.js:294:10)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"},"msg":"Topic not found","time":"2018-10-30T08:53:24.254Z","v":0}
08:53:24.254Z FATAL eatlas: Topic not found
    Error: Topic not found
        at getTopicSlug (/eatlas/server/lib/resource-path.js:21:11)
        at exports.pagePath (/eatlas/server/lib/resource-path.js:37:11)
        at resource (/eatlas/server/lib/generator-utils.js:86:19)
        at exports.getUrl (/eatlas/server/lib/generator-utils.js:407:64)
        at render (/eatlas/server/lib/html-generator.js:93:26)
        at exports.generateTopicHTML (/eatlas/server/lib/html-generator.js:294:10)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:189:7)
```

A voir si ça corrige ton souci côté backoffice...

**Comment by TomBor** [comment]
Merci @jri-sp !
Ça fonctionne, mais j'ai du ajouter un titre EN à toutes les rubriques et pas seulement celle concernée par l'article à publier.
Du coup je pense que l'erreur du `rebuild-site` va disparaitre aussi si tu recommences.

**Comment by jri-sp** [comment]
Oui c'est bon le rebuild-site est passé sans erreur
