### ISSUE TITLE
Erreur avec react-intl

### ISSUE THREAD

**Issue by TomBor** [AtelierCartographie/eatlas#197]
Suite à la mise à jour des dépendances 217e2005f7e9f4f5fa9f277c6c8797f8b5ed9fc6, react-intl semble poser problème car on ne peut plus avoir de preview.
L'erreur suivante est renvoyée : 

```
Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
    at invariant (/Users/80526/www/eatlas/client/node_modules/invariant/invariant.js:40:15)
    at Object.invariantIntlContext (/Users/80526/www/eatlas/client/node_modules/react-intl/dist/utils.js:48:5)
    at Object.children (/Users/80526/www/eatlas/client/node_modules/react-intl/dist/components/injectIntl.js:35:21)
    at ReactDOMServerRenderer.render (/Users/80526/www/eatlas/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:3894:55)
    at ReactDOMServerRenderer.read (/Users/80526/www/eatlas/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:3565:29)
    at renderToStaticMarkup (/Users/80526/www/eatlas/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:4312:27)
    at render (/Users/80526/www/eatlas/server/lib/html-generator.js:133:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by naholyr** [comment]
Oups, je n'ai pas eu ce souci en local, je vais tenter de le reproduire.

**Comment by TomBor** [comment]
Merci !
